// Lista de iconos de Material Symbols más comunes
const MATERIAL_ICONS = [
    'location_on', 'place', 'map', 'explore', 'pin_drop', 'navigation',
    'history', 'history_edu', 'account_balance', 'museum', 'castle',
    'church', 'temple_buddhist', 'synagogue', 'mosque',
    'bookmark', 'bookmark_border', 'star', 'star_border', 'favorite', 'favorite_border',
    'photo_camera', 'camera', 'photo', 'photo_library', 'image', 'collections',
    'restaurant', 'local_cafe', 'local_dining', 'fastfood', 'free_breakfast',
    'park', 'nature', 'forest', 'landscape', 'eco', 'water_drop',
    'architecture', 'apartment', 'business', 'store', 'storefront',
    'directions_walk', 'directions_run', 'directions_bike', 'directions_car',
    'info', 'info_outline', 'help', 'help_outline', 'contact_support',
    'palette', 'brush', 'colorize', 'format_paint',
    'music_note', 'piano', 'theater_comedy', 'festival',
    'book', 'menu_book', 'library_books', 'auto_stories',
    'shopping_bag', 'shopping_cart', 'local_mall',
    'visibility', 'visibility_off', 'remove_red_eye',
    'search', 'zoom_in', 'zoom_out', 'filter_alt',
    'grade', 'stars', 'diamond', 'emoji_events', 'military_tech',
    'lightbulb', 'lightbulb_outline', 'tips_and_updates',
    'shield', 'security', 'verified', 'verified_user', 'lock',
    'account_circle', 'person', 'people', 'group', 'groups',
    'home', 'cottage', 'domain', 'holiday_village',
    'calendar_today', 'event', 'schedule', 'access_time',
    'flag', 'outlined_flag', 'tour', 'luggage',
    'warning', 'error', 'report', 'dangerous',
    'check_circle', 'cancel', 'highlight_off',
    'add_circle', 'remove_circle', 'control_point',
    'arrow_forward', 'arrow_back', 'arrow_upward', 'arrow_downward',
    'chevron_left', 'chevron_right', 'expand_more', 'expand_less',
    'settings', 'tune', 'build', 'handyman',
    'notifications', 'notifications_active', 'notifications_off',
    'mail', 'email', 'send', 'inbox',
    'print', 'cloud', 'cloud_upload', 'cloud_download',
    'phone', 'smartphone', 'tablet', 'computer',
    'wb_sunny', 'nightlight', 'dark_mode', 'light_mode',
    'public', 'language', 'translate', 'travel_explore'
];
